import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ReactQueryProvider } from "@/provider/tanstack/react-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  weight: ["100","200","300","400","500","600","700","800","900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  weight: ["100","200","300","400","500","600","700","800","900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Header/>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
